# Generated by Django 2.2.5 on 2019-10-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('pbi_id', models.AutoField(primary_key=True, serialize=False)),
                ('epic', models.TextField(default=' ')),
                ('user_story', models.TextField(default=' ')),
                ('story_point', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default=' ', max_length=100)),
                ('project_description', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default=' ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=' ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=30)),
                ('password', models.CharField(default=' ', max_length=20)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Role')),
            ],
        ),
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(default=' ')),
                ('effort_hour', models.IntegerField(default=0)),
                ('pbi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.PBI')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint_id', models.AutoField(primary_key=True, serialize=False)),
                ('sprint_number', models.IntegerField(default=0, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
            ],
        ),
        migrations.AddField(
            model_name='pbi',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project'),
        ),
        migrations.AddField(
            model_name='pbi',
            name='sprint_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='application.Sprint'),
        ),
    ]
