# Generated by Django 2.2.6 on 2019-12-04 10:19

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('pbi_id', models.AutoField(primary_key=True, serialize=False)),
                ('epic', models.TextField(blank=True, default=' ')),
                ('user_story', models.TextField(default=' ')),
                ('story_point', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('New', 'Not yet started'), ('Progress', 'In progress'), ('Not', 'Unfinished'), ('Done', 'Completed')], default='New', max_length=50)),
                ('priority', models.IntegerField(blank=True, default=application.models.PBI.getNumOfPbi, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default=' ', max_length=100)),
                ('project_description', models.TextField(default=' ')),
                ('status', models.CharField(choices=[('Progress', 'In progress'), ('Done', 'Completed')], default='Progress', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(default=' ')),
                ('effort_hour', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('New', 'Not yet started'), ('Progress', 'In progress'), ('Not', 'Unfinished'), ('Done', 'Completed')], default='New', max_length=50)),
                ('pbi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.PBI')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=30, unique=True)),
                ('password', models.CharField(default=' ', max_length=20)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('role', models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('D', 'Developer')], default='D', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorksOnTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='WorksOnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint_id', models.AutoField(primary_key=True, serialize=False)),
                ('sprint_number', models.IntegerField(blank=True, default=1, null=True, unique=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Progress', 'In progress'), ('Done', 'Completed')], default='Progress', max_length=50)),
                ('max_effort_hour', models.IntegerField(default=0)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
            ],
        ),
        migrations.AddField(
            model_name='pbi',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project'),
        ),
        migrations.AddField(
            model_name='pbi',
            name='sprint_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Sprint'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(default=' ')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
    ]
