# Generated by Django 2.2.5 on 2019-10-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
    ]
