# Generated by Django 2.2.5 on 2019-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='epic',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='user_story',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
