# Generated by Django 2.2.6 on 2019-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Progress', 'In progress'), ('Done', 'Completed')], default='Progress', max_length=50),
        ),
    ]
