# Generated by Django 2.2.5 on 2019-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ManyToManyField(to='application.Project')),
                ('user_id', models.ManyToManyField(to='application.User')),
            ],
        ),
    ]
