# Generated by Django 2.2.5 on 2019-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20191018_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'Not yet started'), ('Progress', 'In progress'), ('Done', 'Completed')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SM', 'Scrum Master'), ('PO', 'Product Owner'), ('D', 'Developer')], default='D', max_length=30),
        ),
    ]
