# Generated by Django 2.2.5 on 2019-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20191018_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='sprint_number',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=' ', max_length=30, unique=True),
        ),
    ]
