# Generated by Django 2.2.5 on 2019-10-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20191018_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(),
        ),
    ]
