# Generated by Django 2.2.5 on 2019-10-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20191018_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorksOn',
            new_name='WorksOnProject',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
        migrations.CreateModel(
            name='WorksOnTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
    ]
