# Generated by Django 2.2.5 on 2019-10-25 09:01

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20191019_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='priority',
            field=models.IntegerField(default=application.models.PBI.getNumOfPbi),
        ),
    ]
