# Generated by Django 2.2.5 on 2019-10-25 16:57

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20191025_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='priority',
            field=models.IntegerField(blank=True, default=application.models.PBI.getNumOfPbi, null=True),
        ),
    ]
