# Generated by Django 2.2.5 on 2019-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20191026_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('New', 'Not yet started'), ('Progress', 'In progress'), ('Not', 'Unfinished'), ('Done', 'Completed')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'Not yet started'), ('Progress', 'In progress'), ('Not', 'Unfinished'), ('Done', 'Completed')], default='New', max_length=50),
        ),
    ]
