# Generated by Django 2.2.6 on 2019-11-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_sprint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('Progress', 'In progress'), ('Done', 'Completed')], default='Progress', max_length=50),
        ),
    ]
