# Generated by Django 2.2.5 on 2019-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20191108_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='max_effort_hour',
            field=models.IntegerField(default=0),
        ),
    ]
