# Generated by Django 2.2.5 on 2019-11-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_sprint_max_effort_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(default=' ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
    ]
