# Generated by Django 2.2.5 on 2019-12-01 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='application.Project'),
            preserve_default=False,
        ),
    ]
